Fix #1 - Move to packages

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,17 +1,27 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-set -e # fail fast
-[ "$DEBUG" = "true" ] && set -x
+# fail fast
+set -e
 
-# parse params
+# debug
+# set -x
+
+# parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
-BUILDPACK_NAME=cairo
-BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+ENV_DIR=$3
 
-. "$BP_DIR/config/versions.sh"
-. "$BP_DIR/config/s3.sh"
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function topic() {
+  echo "-----> $*"
+}
 
 function indent() {
   c='s/^/       /'
@@ -21,89 +31,70 @@ function indent() {
   esac
 }
 
-function warn() {
-  echo " !     $*"
-}
+PACKAGES="libgif7 libfreetype6 libpixman-1-0 libpango-1.0-0 libcairo2 libfontconfig1 libharfbuzz0b"
 
-function vendor() {
-  binary="$1"
-  path="$2"
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
 
-  echo "Fetching $binary" | indent
-  mkdir -p $path
-  curl $binary --retry 3 --connect-timeout 20 -s -o - | tar xz -C $path -f -
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
 
-  if [ -d "$path/bin" ]; then
-    export PATH=$path/bin:$PATH
-  fi
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
 
-  if [ -d "$path/lib/pkgconfig" ]; then
-    # pkg-config should handle compiler options (if used)
-    export PKG_CONFIG_PATH="$path/lib/pkgconfig:$PKG_CONFIG_PATH"
-  fi
+case "$STACK" in
+  "cedar-14" | "scalingo" | "scalingo-14")
+    APT_FLAGS="--force-yes"
+    ;;
+  "heroku-16" | "heroku-18" | "scalingo-18")
+    APT_FLAGS="--allow-downgrades --allow-remove-essential --allow-change-held-packages"
+    ;;
+  *)
+    error "STACK must be 'cedar-14', 'heroku-16', or 'heroku-18', or 'scalingo', or 'scalingo-18'"
+esac
 
-  # standard paths
-  export CPPPATH="$path/include:$CPPPATH"
-  export CPATH="$path/include:$CPATH"
-  export LIBRARY_PATH="$path/lib:$LIBRARY_PATH"
+topic "Updating apt caches"
+apt-get $APT_OPTIONS update | indent
 
-  export LD_LIBRARY_PATH="$path/lib:$LD_LIBRARY_PATH"
-}
+for PACKAGE in $PACKAGES; do
+  if [[ $PACKAGE == *deb ]]; then
+    PACKAGE_NAME=$(basename $PACKAGE .deb)
+    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
 
-function should_install() {
-  local package="$1"
-  if [ -z "$CAIRO_BUILDPACK_LIBS" ] ; then
-    return 0
+    topic "Fetching $PACKAGE"
+    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
   else
-    echo $CAIRO_BUILDPACK_LIBS | grep -q "$package" ; rc=$?
-    return $rc
+    topic "Fetching .debs for $PACKAGE"
+    apt-get $APT_OPTIONS -y $APT_FLAGS -d install --reinstall $PACKAGE | indent
   fi
-}
+done
 
-function tweak_paths() {
-  export CPPPATH="$BUILD_DIR/vendor/$1/include/$2:$CPPPATH"
-  export CPATH="$BUILD_DIR/vendor/$1/include/$2:$CPATH"
-}
+mkdir -p $BUILD_DIR/.apt
 
-echo "-----> Vendoring binaries"
-should_install "cairo"      && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/cairo-$CAIRO_VERSION.tar.gz"           "$BUILD_DIR/vendor/cairo"
-should_install "freetype"   && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/freetype-$FREETYPE_VERSION.tar.gz"     "$BUILD_DIR/vendor/freetype"
-should_install "giflib"     && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/giflib-$GIFLIB_VERSION.tar.gz"         "$BUILD_DIR/vendor/giflib"
-should_install "pixman"     && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/pixman-$PIXMAN_VERSION.tar.gz"         "$BUILD_DIR/vendor/pixman"
-should_install "pango"      && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/pango-$PANGO_VERSION.tar.gz"           "$BUILD_DIR/vendor/pango"
-should_install "harfbizz"   && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/harfbuzz-$HARFBUZZ_VERSION.tar.gz"     "$BUILD_DIR/vendor/harfbuzz"
-should_install "fontconfig" && vendor "https://$S3_BUCKET.s3.amazonaws.com/$STACK/fontconfig-$FONTCONFIG_VERSION.tar.gz" "$BUILD_DIR/vendor/fontconfig"
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  topic "Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
+done
 
-# node-canvas isn't using pkg-config, so we need to set non-standard paths
-should_install "cairo"    && tweak_paths "cairo"    "cairo"
-should_install "pixman"   && tweak_paths "pixman"   "pixman-1"
-should_install "freetype" && tweak_paths "freetype" "freetype2"
-should_install "pango"    && tweak_paths "pango"    "pango-1.0"
-
-echo "-----> Configuring build environment"
-
-cat <<EOF > export
-export PATH="$PATH:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$LIBRARY_PATH:$LIBRARY_PATH"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:$PKG_CONFIG_PATH"
-export CPPPATH="\$CPPPATH:$CPPPATH"
-export CPATH="\$CPATH:$CPATH"
-EOF
-
-echo "-----> Building runtime environment"
+topic "Writing profile script"
 mkdir -p $BUILD_DIR/.profile.d
-
-cat <<EOF > $BUILD_DIR/.profile.d/$BUILDPACK_NAME.sh
-export PATH="${PATH//$BUILD_DIR//app}:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:${LD_LIBRARY_PATH//$BUILD_DIR//app}"
-export LIBRARY_PATH="\$LIBRARY_PATH:${LIBRARY_PATH//$BUILD_DIR//app}"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:${PKG_CONFIG_PATH//$BUILD_DIR//app}"
-export CPPPATH="\$CPPPATH:${CPPPATH//$BUILD_DIR//app}"
-export CPATH="\$CPATH:${CPATH//$BUILD_DIR//app}"
+cat <<EOF >$BUILD_DIR/.profile.d/puppeteer.sh
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/.apt/usr/include:\$HOME/.apt/usr/include/x86_64-linux-gnu:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
+export PKG_CONFIG_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
 EOF
 
-echo "NOTE: if you are experiencing problems, they may be resulting from a cached"
-echo "library referencing and older version of Cairo. To bypass this with the nodejs"
-echo "buildpack, set NODE_MODULES_CACHE=false to force node-canvas to be rebuilt"
-echo "against newer versions of the libraries."
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
+export LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$BUILD_DIR/.apt/usr/include/x86_64-linux-gnu:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+export PKG_CONFIG_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
+
+#give environment to later buildpacks
+export | grep -E -e ' (LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$LP_DIR/export"
+
+topic "Rewrite package-config files"
+find $BUILD_DIR/.apt -type f -ipath '*/pkgconfig/*.pc' | xargs --no-run-if-empty -n 1 sed -i -e 's!^prefix=\(.*\)$!prefix='"$BUILD_DIR"'/.apt\1!g'
